name: flutter_firebase_quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  image_picker: ^1.1.2
  shared_preferences: ^2.5.1
  path_provider: ^2.1.5
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/quizdom.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/quizdom.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
